version: '3'
services:
  database:
    image: 'mysql:8.0'
    volumes:
      - app-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php2024w06
    ports:
      - '3306:3306'
  pma:
    depends_on:
      - database
    image: phpmyadmin:5
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root

volumes:
  app-database:
